<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ImportGroup Label="PropertySheets" />
  <PropertyGroup Label="UserMacros">
    <OutputConfigName>$(Configuration)_$(Platform)</OutputConfigName>
    <SourceDir>$(ProjectDir)Source\</SourceDir>
    <BinariesDir>$(ProjectDir)Bin\$(OutputConfigName)\</BinariesDir>
    <IntermediateDir>$(ProjectDir)Intermediate\$(OutputConfigName)\</IntermediateDir>
    <LibraryDir>$(SolutionDir)Lib\</LibraryDir>
  </PropertyGroup>
  <PropertyGroup>
    <OutDir>$(BinariesDir)</OutDir>
    <IntDir>$(IntermediateDir)</IntDir>
  </PropertyGroup>
  <ItemDefinitionGroup>
    <ClCompile>
      <WarningLevel>Level4</WarningLevel>
    </ClCompile>
  </ItemDefinitionGroup>
  <ItemDefinitionGroup>
    <ClCompile>
      <TreatWarningAsError>true</TreatWarningAsError>
    </ClCompile>
  </ItemDefinitionGroup>
  <ItemDefinitionGroup>
    <ClCompile>
      <MultiProcessorCompilation>true</MultiProcessorCompilation>
      <Optimization>Custom</Optimization>
      <WholeProgramOptimization>false</WholeProgramOptimization>
      <ConformanceMode>true</ConformanceMode>
      <UseStandardPreprocessor>true</UseStandardPreprocessor>
      <FloatingPointModel>Fast</FloatingPointModel>
      <StringPooling>true</StringPooling>
      <MinimalRebuild>false</MinimalRebuild>
      <ControlFlowGuard>Guard</ControlFlowGuard>
      <LanguageStandard>stdcpplatest</LanguageStandard>
      <LanguageStandard_C>stdc17</LanguageStandard_C>
      <AdditionalOptions>/utf-8 %(AdditionalOptions)</AdditionalOptions>
      <AdditionalIncludeDirectories>
      </AdditionalIncludeDirectories>
      <PreprocessorDefinitions>MKPLATFORM_WIN64;_UNICODE;UNICODE;%(PreprocessorDefinitions)</PreprocessorDefinitions>
      <DebugInformationFormat>ProgramDatabase</DebugInformationFormat>
    </ClCompile>
    <Link>
      <AdditionalLibraryDirectories>
      </AdditionalLibraryDirectories>
    </Link>
    <Midl>
      <WarningLevel>0</WarningLevel>
    </Midl>
  </ItemDefinitionGroup>
  <ItemGroup>
    <BuildMacro Include="OutputConfigName">
      <Value>$(OutputConfigName)</Value>
    </BuildMacro>
    <BuildMacro Include="SourceDir">
      <Value>$(SourceDir)</Value>
    </BuildMacro>
    <BuildMacro Include="BinariesDir">
      <Value>$(BinariesDir)</Value>
    </BuildMacro>
    <BuildMacro Include="IntermediateDir">
      <Value>$(IntermediateDir)</Value>
    </BuildMacro>
    <BuildMacro Include="LibraryDir">
      <Value>$(LibraryDir)</Value>
    </BuildMacro>
  </ItemGroup>
</Project>