<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <ImportGroup Label="PropertySheets" />
  <PropertyGroup Label="UserMacros">
    <LibraryDir>$(SolutionDir)Lib\</LibraryDir>
  </PropertyGroup>
  <PropertyGroup>
    <PublicIncludeDirectories>$(SourceDir)Include\</PublicIncludeDirectories>
  </PropertyGroup>
  <ItemDefinitionGroup>
    <ClCompile />
    <ClCompile>
      <AdditionalIncludeDirectories>$(LibraryDir)EventPP\include;$(LibraryDir)SpdLog\include;$(SourceDir)Private;$(SourceDir)Include;%(AdditionalIncludeDirectories)</AdditionalIncludeDirectories>
    </ClCompile>
    <Link />
  </ItemDefinitionGroup>
  <ItemGroup>
    <BuildMacro Include="LibraryDir">
      <Value>$(LibraryDir)</Value>
    </BuildMacro>
  </ItemGroup>
</Project>